version: "3"

services:
    python:
        build:
            context: .
            dockerfile: ./docker/python/Dockerfile
            target: development
        volumes:
            - ./waseda-moodle-scheduler:/waseda-moodle-scheduler
            - ./log/waseda-moodle-scheduler:/var/log/waseda-moodle-scheduler
        ports:
            - "8000:80"
        environment:
            DB_NAME: "waseda_moodle_scheduler"
            DB_USER: "user"
            DB_PASSWORD: "password"
            DB_HOST: "mysql"
            DB_PORT: "3306"
        env_file: ./waseda-moodle-scheduler/.env
        depends_on:
            - mysql
    mysql:
        platform: linux/x86_64
        build:
            dockerfile: ./docker/mysql/Dockerfile
            context: .
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_DATABASE: "waseda_moodle_scheduler"
            TZ: "Asia/Tokyo"
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/conf.d:/etc/mysql/conf.d
            - mysql:/var/lib/mysql
            - ./log/mysql:/var/log/mysql

volumes:
    mysql:
        driver: local
