# Generated by Django 3.1.7 on 2021-03-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='event',
            name='uid',
            field=models.CharField(max_length=100, unique=True, verbose_name='uid'),
        ),
    ]
